### ISSUE TITLE
resync against upstream pathlib?

### ISSUE THREAD

**Issue by jrobeson** [mcmtroffaes/pathlib2#10]
I was doing a comparison between pathlib as exists in python git mirror and in this repository. Are you still planning on doing any more releases to keep up with changes up to 3.5?

**Comment by mcmtroffaes** [comment]
Yep, definitely, I mean to keep this up to sync. Everything from 3.5.0 should be there; see https://github.com/mcmtroffaes/pathlib2/pull/4 I'll check what can be merged from 3.5.2.

**Comment by mcmtroffaes** [comment]
The develop branch should now have all the new goodies from 3.5.2. Can you check if you see anything still missing?

**Comment by jrobeson** [comment]
I think so.   I wonder how you'll implement 3.6 compat when the time comes.
