### ISSUE TITLE
UnicodeEncodeError in Path() for a path with non-ASCII characters

### ISSUE THREAD

**Issue by native-api** [mcmtroffaes/pathlib2#13]
```
>>> pathlib2.Path(u'/c/Documents and Settings/User/\u041c\u043e\u0438 \u0434\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u044b/.ipython/profile_default/db')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pathlib2.py", line 1095, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python2.7/site-packages/pathlib2.py", line 760, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python2.7/site-packages/pathlib2.py", line 748, in _parse_args
    parts.append(str(a))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 31-33: ordinal not in range(128)
```

As you may have guessed, this appears when starting `ipython` in Cygwin if Cygwin's home dir is a junction to the Windows one.

Since `str` is Unicode in Python 3, I believe the error is specific to the backport.

**Comment by phretor** [comment]
Not only with ipython. It seems that pathlib2 is performing "automatic" encoding.

**Comment by mcmtroffaes** [comment]
Sorry for the delay in my reply here.

Perhaps this issue https://bugs.python.org/issue21127 which introduced the str cast sheds some more light. The constructor is clearly written to expect a (subclass of) str. Also see:

https://bitbucket.org/pitrou/pathlib/src/1f9672002e3a5e54c48dd48912cc6d45f8a2137d/pathlib.py?at=default&fileviewer=file-view-default#pathlib.py-745

So in the old pathlib, unicode won't work either for Python 2.7.

It would make sense for me if paths were represented by unicode objects in Python 2, instead of str objects, however that would be a pretty invasive and backwards incompatible change.

Thoughts?

**Comment by native-api** [comment]
It would indeed make sense to use Unicode wherever possible - internally, at the very least.

* First, Python 3 does, so the behaviour would match the upstream library's.
* Second, it's perfectly valid to have a path that's not representable in any single 8-bit encoding, both [in Windows](https://msdn.microsoft.com/en-us/library/windows/desktop/dd317748%28v=vs.85%29.aspx) and [Linux](https://www.cl.cam.ac.uk/~mgk25/unicode.html).  

Windows [apparently uses `WideCharToMultiByte`](https://msdn.microsoft.com/en-us/library/windows/desktop/dd317748%28v=vs.85%29.aspx) (in Python, it's the `mbcs` encoding) to convert things for its ANSI APIs which maps all unrepresentable characters to question marks. Even if these might work to access the path, one cannot create that path with them, so anyone working with such paths without Unicode is shooting themselves in the foot.
Linux kernel treats paths as sequences of bytes (only '/' and '\0' are treated specially), any program that has to deal with characters proper (including Python) uses locale. Any programs that don't care about Unicode will see the raw bytes.

So, in Linux, it's a no-brainer, and in Windows, sticking to `str` would be more trouble than it's worth. 

---

To minimize code changes from upstream, I am thinking about something like `str=six.text_type` at the beginning. Explicit type checks would still need to be altered but seems you have those covered already.

`intern`s are a problem, too. In my local copy, I just replaced them with a no-op. If we're going unicode, they'll be useless anyway.

**Comment by mcmtroffaes** [comment]
I've thought about this a bit more. For now, I'd suggest converting unicode to str with sys.filesystemencoding to keep using str internally (see https://docs.python.org/2/library/sys.html#sys.getfilesystemencoding ).

I agree in principle it would be cleaner to use unicode internally everywhere, but that's potentially a major refactoring of the code. I wouldn't be against doing this in the long term. So, quick solution for now, we can then think about a better long term solution later. Is that ok?

**Comment by native-api** [comment]
This fixes the problem I'm currently having and I don't have any paths not representable in `filesystemencoding`, so fine by me.
I would prefer to close the issue once and for all, but if the way proved to be yet unclear, okay.

**Comment by mcmtroffaes** [comment]
Ok, thanks for the feedback and helping with the brainstorming - much appreciated! I may revisit this later if I get reports from folks wanting to use pathlib2 for paths that aren't representable by their filesystem encoding, but probably that use case is pretty low...

**Comment by Suor** [comment]
Oh, this is such a headache for me. I have code like:
```python
fname = path.name + FILE_SUFFIX
```
And it doesn't work since `path.name` is bytes in Python 2 and I need to support both Pythons and use unicode everywhere already.

**Comment by Suor** [comment]
**P.S.** And I am using pure paths.
