### ISSUE TITLE
Explicit license in source files

### ISSUE THREAD

**Issue by pcpa** [mcmtroffaes/pathlib2#14]
I am working on having a python-pathlib2 package in Fedora.
[Review Request: python-pathlib2 - Object-oriented filesystem paths](https://bugzilla.redhat.com/show_bug.cgi?id=1406962)
  One issue is about having only a LICENSE.rst file.

  It should be enough to have a confirmation that all files are
under MIT license.
  Otherwise, something like 3 lines header should be enough,
as there is already the LICENSE.rst file. For example:

```
# Copyright (c) 2014 Matthias C. M. Troffaes
# Copyright (c) 2012-2014 Antoine Pitrou and contributors
# Distributed under the terms of the MIT License.
```

**Comment by mcmtroffaes** [comment]
Thanks for packaging pathlib2 for Fedora!

Yes, all files are under the MIT license. I'll add a license header to every source file, indeed that's good practice, and thanks for suggesting it.
