### ISSUE TITLE
You cannot have a py2.py3-none-any.whl if there are version dependent dependancies

### ISSUE THREAD

**Issue by AvdN** [mcmtroffaes/pathlib2#20]
Installing `pathlib2` version 2.2.0 using `pip` on a Python 3.5 or Python 3.6 will get the wheel and thus install `scandir`. Because the setup.py contains code that depends on the version of Python that runs setup.py, no single py2.py3-none-any wheel can be used as there is no such version dependency within the wheel's metadata file.

This is especially harmful because `scandir` (version 1.4) includes test data in its zip file for which the filenames generates errors on extraction on Docker image Ubuntu 16.04 with Python3 installed. Scandir also doesn't seem to be able to handle systems without compiler. 

This broke one of Docker containers and my current solution is to pin the install on pathlib2. 
The quick solution would be to remove the wheel file from PyPI any new versions should remove the dependency on scandir in `setup.py` until scandir has solved its problems.

**Comment by mcmtroffaes** [comment]
Hmmm, yes... I think we need this: https://wheel.readthedocs.io/en/latest/index.html#defining-conditional-dependencies

**Comment by AvdN** [comment]
I had not seen this (but then I don't reread the doc/spec for wheels on every minor release), but it looks good. It makes sense to not require separate wheel files if only the dependencies are different.

Since this functionality could already be done in `setup.py` and also used to be in `bdist_wheel/setup.cfg` it looks like they are re-inventing the wheel ;-)

**Comment by AvdN** [comment]
I unpinned pathlib2 in my original container and with 2.2.1 it correctly builds again. Thanks

**Comment by mcmtroffaes** [comment]
Great - thanks for confirming!
