### ISSUE TITLE
resovle() does not throw OSError when the path does not exits

### ISSUE THREAD

**Issue by anuragagarwal561994** [mcmtroffaes/pathlib2#23]
On Mac resolve throws OSError when the path does not exists but not linux.

Python: 2.7

**Comment by mcmtroffaes** [comment]
Sorry for the delay in my reply here. Does pathlib from the standard library feature the same behaviour on mac? If so, please report to upstream. If not, well, I don't have a mac for testing, but a mac specific patch would be welcome.

**Comment by anuragagarwal561994** [comment]
Thanks for your response, I will check and revert back on same.

**Comment by mcmtroffaes** [comment]
I've just resynced against upstream, so if this was fixed upstream then it should also have been fixed in 2.3.0. If this was fixed upstream but it still persists in this version, feel free to reopen.
