### ISSUE TITLE
Pathlib2 2.2.1 fails to install on TravisCI, thinks it only supports Python3

### ISSUE THREAD

**Issue by relwell** [mcmtroffaes/pathlib2#24]
You can refer to https://github.com/solrcloudpy/solrcloudpy/pull/41 as a history of me trying to figure out why my project's builds are failing, and isolating it to version 2.2.1 instead of 2.2.0. My project has IPython as dependency, which has Pathlib2 as a dependency. Since I wasn't pegged to 2.2.0, previous builds passed, but builds that use 2.2.1 fail.

You can see in [this build in particular](https://travis-ci.org/solrcloudpy/solrcloudpy/builds/202455533#L264-L273) that version 2.2.1 fails because it now claims to only support Python version 3.5 or greater.

If we have introduced a breaking change where pathlib2 no longer supports 2.7, this probably should be a major version bump rather than a patch bump.

**Comment by mcmtroffaes** [comment]
Sorry for the delay in responding here. Pip on travis is outdated and doesn't support environment markers. Just run ``pip install -U setuptools`` as part of your install section, and the error should go away.

**Comment by mcmtroffaes** [comment]
Fixed here: https://github.com/solrcloudpy/solrcloudpy/pull/43
