### ISSUE TITLE
pathlib.resolve(strict=False) only includes first child

### ISSUE THREAD

**Issue by phill-85** [mcmtroffaes/pathlib2#28]
This issue has been fixed in Python, just wanted to make sue you guys were aware of it!
http://bugs.python.org/issue30177

**Comment by mcmtroffaes** [comment]
Thanks for flagging. I'll resync with upstream.

**Comment by mcmtroffaes** [comment]
The latest version on PyPI should now include this fix. Thanks again for reporting!

**Comment by phill-85** [comment]
Fantastic, thanks for the quick response!
