### ISSUE TITLE
os.scandir only supported by python 3.6

### ISSUE THREAD

**Issue by marbre** [mcmtroffaes/pathlib2#31]
I recently tried to version bump the Gentoo Linux pathlib2 ebuild. Unfortunately, the tests fail with `ImportError: No module named scandir`. With a quick look to the python docs it seems that `os.scandir` is only available with python 3.6. I would suggest to either drop scandir or modify the supported python versions in the setup.py accordingly.

**Comment by mcmtroffaes** [comment]
For Python 3.4 and older the scandir module ought to be used:

https://github.com/mcmtroffaes/pathlib2/blob/develop/setup.py#L48
https://github.com/mcmtroffaes/pathlib2/blob/develop/pathlib2.py#L43

My guess is that you're trying to install pathlib2 with a too old version of setuptools which doesn't support environment markers, or a too new version that uses the new syntax and maybe dropped the old syntax:

https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-platform-specific-dependencies

Naturally setup.py should be updated to use that syntax. The current extras_require syntax dates back from the days where setuptools didn't support environment markers in install_requires. Does this help?

I'll get around to updating setup.py at some point to the new syntax.

**Comment by mcmtroffaes** [comment]
Can you check if the branch at pull request #32 fixes your problem?

**Comment by marbre** [comment]
Thank you very much for your reply. I actually missed the line in the setup.py. The Gentoo ebuild system actually does not pulls in dependencies defined in the setup.py and the maintainer of the ebuild has to add the deps to the ebuild itself. However, just missed this dependency. Therefore, we simply have to add an ebuild providing scandir and add it to the to dependencies.

**Comment by mcmtroffaes** [comment]
Ok. Thanks for getting back to me, I'm glad you have it resolved on your end!
