### ISSUE TITLE
Unicode issues

### ISSUE THREAD

**Issue by Dobatymo** [mcmtroffaes/pathlib2#34]
Python 2.7.13, pathlib2-2.3.0

If the the input to path is unicode, the output of Path functions is not unicode but str. In python 3 both will be unicode.

In python 2 str input should result in str, unicode in unicode output. This would also be consistent to how python 2 stdlib functions work.

```python
>>> from pathlib2 import Path
>>> Path(u"/asd").parts
('\\', 'asd')
>>> Path(u"/asd").name
'asd'
```

**Comment by mcmtroffaes** [comment]
What you're asking could be implemented by storing internally, for python 2, whether a path was created using str or unicode, and then converting to unicode on the fly for every function that currently returns a str. It's not clear to me that this is the right thing to do. Unicode on python 2 has been discussed at length here: https://github.com/mcmtroffaes/pathlib2/issues/13 - I haven't arrived at a clear conclusion.

To be honest, I'd prefer to use unicode internally everywhere, and so for python 2 to convert str to unicode using the file system encoding as soon as the data is received from the user. That would make it maximally consistent with the python 3 version. But it would be a pretty invasive (and backwards incompatible) change.

The decision to use of str internally to store the paths dates back from the original pathlib module, which pathlib2 was forked from, so it's been around for a very long time.

**Comment by Dobatymo** [comment]
Thanks for your reply. I can see that backwards compatibility is important.

**Comment by waylan** [comment]
This libs purported goal is to "support the full stdlib Python API." That API includes returning all strings as Unicode. As it is now, it is completely useless to me as I have to jump through hopes to support Python 2.7 with the same behavior as Python 3. Wish I would have realized this sooner. Now I have to rip it out and go back to using `os.path` functions. As least they provide consistent results across Python 2 and 3.

**Comment by waylan** [comment]
Note that the Python Documentation states under [Unicode Filenames][1]

> The `os.listdir()` function returns filenames and raises an issue: should it return the Unicode version of filenames, or should it return bytes containing the encoded versions? `os.listdir()` will do both, depending on whether you provided the directory path as bytes or a Unicode string. If you pass a Unicode string as the path, filenames will be decoded using the filesystem’s encoding and a list of Unicode strings will be returned, while passing a byte path will return the filenames as bytes. 

Note that the [Python 2.7 docs][2] say the same thing. And, in my experience, that same behavior is consistent across the path handling functions in the standard library. I would expect any "backport" to have that same behavior as well. The obvious benefit is that I never have to worry about the filesystem encoding as long as I always work in Unicode. 

I understand that keeping track of what type was provided so as to always return the same type is more complicated, but IMO any other behavior is a bug and makes the lib useless.

[1]: https://docs.python.org/3/howto/unicode.html#unicode-filenames
[2]: https://docs.python.org/2.7/howto/unicode.html#unicode-filenames

**Comment by mcmtroffaes** [comment]
I can't quite remember why this is still open. :-) And yes, @asanakoy indeed that behaviour would be more logical (as discussed above) and indeed unfortunately that won't be backward compatible.

I'm afraid this design flaw of using bytes for paths in Python 2 but unicode for paths in Python 3 has been part of pathlib since the project was started, and there's no easy way now to change that without a major refactoring and introducing backward incompatibility. Given that Python 2 is going eol very soon now, it seems not worth doing the effort of redesigning the library, as such redesign will have little to no uptake anyway.
