### ISSUE TITLE
Consider `tox` for testing

### ISSUE THREAD

**Issue by clbarnes** [mcmtroffaes/pathlib2#36]
As a backport library, pathlib2 rightly tests against many different versions of python, and as such contains a complex system of shims filling in and renaming stdlib stuff. Running the tests to make sure that these all still work after any change means maintaining 9 different virtualenvs, which is a hassle and a barrier to entry for contributors.

[Tox](https://tox.readthedocs.io/en/latest/) (and its extension for parallel testing, [detox](https://pypi.python.org/pypi/detox)) could control setting up and tearing down all the different virtualenvs, making it *much* easier to test locally, and keeping the test environment consistent between the local and CI environments.

**Comment by clbarnes** [comment]
Agh, tox only works for 2.7 and 3.4+. Never mind then.

**Comment by clbarnes** [comment]
Having just checked it out, 2.6 and 3.3 are both EOL so I think dropping support for them is reasonable. Using the same build matrix for local and CI testing has significant benefits, I think.

**Comment by clbarnes** [comment]
Having just checked it out, 2.6 and 3.3 are both EOL so I think dropping support for them is reasonable. Using the same build matrix for local and CI testing has significant benefits, I think.

**Comment by mcmtroffaes** [comment]
Well, to be honest, there's so much stuff in the build matrix that I only run a single test locally, and let travis/appveyor handle the rest. But I can see the use of more extensive local testing. I'd be happy to carry a simple self-contained standalone tox.ini file in the repository for that purpose (preferably not one that refers to makefiles, for maximum portability also to windows).

**Comment by mcepl** [comment]
To be completely honest, I wonder what's the raison d'être of this package outside of Python 2.* universe (which will shutdown in slightly more than a year). With the hat of the SUSE Python guy I have to admit a strong dislike for all ``*2`` packages.

There may be some excuse for those were the upstream development is done outside of the main CPython repo, where only snapshots are send from time to time, but that is not the case here, is it?

The situation here is even more dire as this package now supports (in Python 3.* universe) only those versions which already have ``pathlib`` natively. Wouldn't some deprecation and winding down be the most appropriate plan for the future of this package?

**Comment by mcmtroffaes** [comment]
Closing for now. Please feel free to submit a tox.ini file via a pull request if you still would like to see this address.
