### ISSUE TITLE
Python 3.6.4: AttributeError: module 'test.support' has no attribute 'android_not_root'

### ISSUE THREAD

**Issue by mgorny** [mcmtroffaes/pathlib2#39]
When trying to run tests on Python 3.6.4:

```
Traceback (most recent call last):
  File "test_pathlib2.py", line 48, in <module>
    android_not_root = support.android_not_root
AttributeError: module 'test.support' has no attribute 'android_not_root'
```

Didn't anyone tell you that using private Python modules is a recipe for disaster?

**Comment by kapsh** [comment]
Fix this test please. This attribute was removed in 3.6: https://github.com/python/cpython/pull/4380/files#diff-ca2bc62863abb3c22fb09acd2539c12dL23

**Comment by mcmtroffaes** [comment]
This was already fixed back in January 2018, and will be included in the next release:

 https://github.com/mcmtroffaes/pathlib2/pull/37/commits/7cde10e40ed54d27bbcae43d0b4603ef422e2f01

**Comment by kapsh** [comment]
@mcmtroffaes thank you, it's all good now. I didn't pay attention that previous release was quite long ago.

**Comment by mcmtroffaes** [comment]
Yeah indeed, no problem. You reminded me to get that release out of the door, so, thanks!
