### ISSUE TITLE
Pathlib does not compare Windows and MinGW paths as equal

### ISSUE THREAD

**Issue by Paebbels** [mcmtroffaes/pathlib2#43]
`pathlib` does not compare absolute paths from Windows and MinGW as equal.

Windows absolute path: `C:\path\to\tool`  
MinGW absolute path: `/c/path/to/tool`  
Cygwin absolute path: `/cygdrive/c/path/to/tool`  

I consider this a bug, because it's the same bug but 3 different writings and pathlib is not able to identify the equality.

**This issues is also listed here:**

* [Python issue 33890](https://bugs.python.org/issue33890) - Pathlib does not compare Windows and MinGW paths as equal
* [How to compare absolute Windows and MinGW paths with pathlib?](https://stackoverflow.com/questions/50900779/how-to-compare-absolute-windows-and-mingw-paths-with-pathlib)

**Comment by mcmtroffaes** [comment]
This repository only deals with issues that occur in this backport, and that do not occur not in the standard Python pathlib module (see the readme). Once this is fixed upstream, the fix will naturally be incorporated in a future release of pathlib2.
