### ISSUE TITLE
Permission to add stubs for pathlib2 to typeshed

### ISSUE THREAD

**Issue by li-dan** [mcmtroffaes/pathlib2#44]
I am interested in adding a [PEP 484](https://www.python.org/dev/peps/pep-0484/) stub file for pathlib2 to the [typeshed](https://github.com/python/typeshed). Before accepting stubs for third party libraries, they need the maintainers to give permission, as detailed [here](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#adding-a-new-library).

Is it okay to add a stub file for pathlib2 to the typeshed?

**Comment by mcmtroffaes** [comment]
Sure, no problem!
