### ISSUE TITLE
Pathlib2 switched to new syntax in setup.py without bumping major or minor version

### ISSUE THREAD

**Issue by zvezdan** [mcmtroffaes/pathlib2#46]
The switch to new syntax for conditional dependencies in _pathlib2-2.3.2_ causes issues to automated build tooling that uses _pex_. This line: https://github.com/mcmtroffaes/pathlib2/blob/develop/setup.py#L47 used to be done in `extras_require` instead of `install_requires`.

Recent versions of _setuptools_ and _wheel_ are able to parse this new syntax, but older versions enforced by _pex_ are not: https://github.com/pantsbuild/pex/blob/v1.4.5/pex/version.py#L9
Until recently, _wheel_ was also forced to version that is not able to parse new syntax: https://github.com/pantsbuild/pex/blob/v1.4.4/pex/version.py#L11

This would be less of an issue if _pathlib2_ bumped a version in major or minor instead of just patch part of the version number. This is a breaking change for build systems that worked just fine with _pathlib2-2.3.0_.

I'm asking if we can do one or both of the following to fix this issue.

1. Revert to `extras_require` in version 2.3.x of _pathlib_, preferably 2.x and perhaps use it only for the next major version?
2. Perhaps avoid using the new syntax entirely? This is a backport package and those who need a backport package most probably do not have up-to-date environment anyway to parse the new features.

**Comment by mcmtroffaes** [comment]
Thanks for reporting and sorry for the delay in the response here. I've just pushed a release that uses the old deprecated syntax.
