### ISSUE TITLE
Calling Path.exists() on non-existent drive raises WindowsError

### ISSUE THREAD

**Issue by assumptionsoup** [mcmtroffaes/pathlib2#47]
Any idea why this is happening?

```
>>> import pathlib2 as pathlib
>>> pathlib.Path(r"E:\Whatever\blah.txt").exists()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "P:\common\rez\packages\pathlib2\2.3.2\pathlib2\__init__.py", line 1549, in exists
    self.stat()
  File "P:\common\rez\packages\pathlib2\2.3.2\pathlib2\__init__.py", line 1356, in stat
    return self._accessor.stat(self)
  File "P:\common\rez\packages\pathlib2\2.3.2\pathlib2\__init__.py", line 541, in wrapped
    return strfunc(str(pathobj), *args)
WindowsError: [Error 21] The device is not ready: 'E:\\Whatever\\blah.txt'
>>> import os
>>> os.path.exists(r"E:\Whatever\blah.txt")
False
>>> pathlib.Path(r"C:\whatever\blah.txt").exists()
False
```

I tested this with version 2.3.2 and the latest commit 87f9a0e8c69a593c92d02aec9e4d6baefe012252

**Comment by mcmtroffaes** [comment]
No idea... I do note that standard python has precisely same implementation for the ``exists()`` function i.e. uses a stat call to determine whether a path exists. Can you try to see if

```python
import pathlib
pathlib.Path(r"E:\Whatever\blah.txt").exists()
```

gives the same error? If so (and I expect it will), then you'll need to take this upstream.

**Comment by assumptionsoup** [comment]
Ah, you're right. This is an upstream issue. I'm seeing the same issue with `pathlib` in python3.

**Comment by mcmtroffaes** [comment]
Ok. When it gets fixed there, the fix should land back here as well with the next upstream sync.

**Comment by assumptionsoup** [comment]
Sounds good. I've gone ahead and created an issue upstream in the python tracker https://bugs.python.org/issue35692

**Comment by mcmtroffaes** [comment]
The fix is now in develop, and will be included with the next release. It should work now, if not, do let me know and I'll look into it. Thanks once more for engaging with upstream to get this addressed!
