### ISSUE TITLE
A support for absolute path in `glob()` is required

### ISSUE THREAD

**Issue by minherz** [mcmtroffaes/pathlib2#48]
Currently, it is required to split a wildcard path to a directory part before to be able to list all relevant files using `glob()` call. It will be useful to feature support of the absolute path in `glob()` as well as relative.

**Comment by mcmtroffaes** [comment]
Apologies for the late response. Is this an issue unique to pathlib2, or does it occur both with stdlib pathlib (on Python 3) and pathlib2? (If it occurs in stdlib pathlib in as well, then you'll need to work with upstream cpython to get this fixed.)

If it only happens in pathlib2, could you give me a quick few lines of Python code to reproduce the issue?

**Comment by minherz** [comment]
I do not know if the following statement works with pathlib2 or pathlib but the name of the imported package in yaml is `pathlib2`.
```python
from pathlib import Path
```
I was looking for a functionality that can produce a valid result from the following statement:
```python
list(Path(".").glob("/etc/test/*.yml")
```
But looking on it now, it seems wrong that it will work and it also can be easily mitigated by using:
```python
list(Path("/").glob("etc/test/*.yml")
```
So, I am closing this issue 😄

**Comment by mcmtroffaes** [comment]
Ok, glad you figured this out!
