### ISSUE TITLE
need py3.5 pathlib .expanduser method

### ISSUE THREAD

**Issue by scienceopen** [mcmtroffaes/pathlib2#5]
In Python 3.5.0:
```
  from pathlib import Path
  f = Path('~')
  f.expanduser()
```
gives the home directory full path.

In Python 3.4.3 with pathlib2 2.0.1:
```
  from pathlib2 import Path
  f = Path('~')
  f.expanduser()
```
gives `AttributeError: 'PosixPath' object has no attribute 'expanduser'`

**Comment by mcmtroffaes** [comment]
This is already in the develop branch - have you tested this? I'll do a new release if that works for you.

**Comment by scienceopen** [comment]
Hi Matthias no I don't need a release, though others might find that handy. I'm a frequent expanduser user.                                                                                                                                                                                                                                                                                                                                        M.H.(202) 765-4770https://keybase.io/michaelhirsch                                                                                                                                                                                                                From: Matthias C. M. TroffaesSent: Wednesday, November 4, 2015 04:06To: mcmtroffaes/pathlib2Reply To: mcmtroffaes/pathlib2Cc: Michael HirschSubject: Re: [pathlib2] need py3.5 pathlib .expanduser method (#5)This is already in the develop branch - have you tested this? I'll do a new release if that works for you.

—Reply to this email directly or view it on GitHub.

**Comment by mcmtroffaes** [comment]
Thanks for the quick response. So does the develop branch work for you? (Sorry if that question wasn't clear from my previous comment.)

**Comment by scienceopen** [comment]
Yes develop is fine but I think others would benefit by a release, helping accelerate adoption of pathlib. Any particular reason not to release now?                                                                                                                                                                                                                                                                                                                                        M.H.(202) 765-4770https://keybase.io/michaelhirsch                                                                                                                                                                                                                From: Matthias C. M. TroffaesSent: Wednesday, November 4, 2015 05:15To: mcmtroffaes/pathlib2Reply To: mcmtroffaes/pathlib2Cc: Michael HirschSubject: Re: [pathlib2] need py3.5 pathlib .expanduser method (#5)Thanks for the quick response. So does the develop branch work for you? (Sorry if that question wasn't clear from my previous comment.)

—Reply to this email directly or view it on GitHub.

**Comment by mcmtroffaes** [comment]
The only reason to postpone release was your bug report and it wasn't clear whether you tested against develop or not. ;-) Now that's confirmed, I'll roll a release.

**Comment by mcmtroffaes** [comment]
Released: https://pypi.python.org/pypi/pathlib2

**Comment by scienceopen** [comment]
Thanks I'll start using it for my programs, which I currently strive to make Python 3.4/3.5 compatible (starting to deprecate Python 2.7 support by my code as New Year's resolution)
