### ISSUE TITLE
getfilesystemencoding can be None, causing error

### ISSUE THREAD

**Issue by wryun** [mcmtroffaes/pathlib2#59]
In Python before 3.2, it's possible to get None from this. However AWS Codebuild is setting things up, this causes pathlib2 to explode:

```
...
  File "/codebuild/output/src991325250/src/github.com/.../ve-web/local/lib/python2.7/site-packages/pathlib2/__init__.py", line 928, in _make_child 
    drv, root, parts = self._parse_args(args) 
  File "/codebuild/output/src991325250/src/github.com/.../ve-web/local/lib/python2.7/site-packages/pathlib2/__init__.py", line 885, in _parse_args 
    parts.append(a.encode(sys.getfilesystemencoding())) 
TypeError: encode() argument 1 must be string, not None 
```

**Comment by mcmtroffaes** [comment]
Thanks for reporting. I cannot reproduce the problem but I see it's possible according to the documentation: https://docs.python.org/2/library/sys.html#sys.getfilesystemencoding

I've seen other code in the cpython implementation fall back to ascii in these cases (see for instance https://github.com/python/cpython/commit/3741effcf8de2af3224e20af2865b7e378e59855), I'll add a patch to do the same in pathlib2.

**Comment by mcmtroffaes** [comment]
Could you test and confirm that https://github.com/mcmtroffaes/pathlib2/commit/59e893e2979fb59212b4bca97a5418e3409333b4 fixes the issue that you reported?

**Comment by wryun** [comment]
Yes, this fixes the issue for me - thanks for the fast response!

**Comment by mcmtroffaes** [comment]
Splendid. Thanks for confirming!

**Comment by mcmtroffaes** [comment]
FYI I've just pushed a new release including the fix.
