### ISSUE TITLE
dropping python 2.7

### ISSUE THREAD

**Issue by mcmtroffaes** [mcmtroffaes/pathlib2#71]
I thought I write down my thoughts on this backport w.r.t. dropping Python 2.7 as this might need some discussion.

The current code for pathlib2 contains a lot of extremely ugly (and type-annotation unfriendly) hacks relating to Python 2.7. If we drop it, there's no need to keep those hacks around, resulting in cleaner code with less potential sources for bugs, and with more helpful type annotations. So, instead of manually removing those hacks, I'd actually suggest to make a fresh backport by taking the current cpython pathlib module and simply patching it to work on 3.6+. I believe this will be the easiest route going forward.

**Comment by graingert** [comment]
I agree, I think it's worth cutting one last release for Python 2.7 then dropping it immediately afterward

**Comment by mcmtroffaes** [comment]
Thanks @graingert. I wonder if it is actually still worth cutting a release for Python 2.7? As far as I know, nobody is waiting for it, although I'd happily stand corrected.

**Comment by graingert** [comment]
Mainly as a minimal step to check the jazzband release process
