### ISSUE TITLE
use “pathlib” as module name

### ISSUE THREAD

**Issue by flying-sheep** [mcmtroffaes/pathlib2#8]
i want to use

```py
from pathlib import Path
Path('foo').mkdir(exist_ok=True)
```

instead of

```py
try:
    from pathlib import Path
except ImportError:
    from pathlib2 import Path
Path('foo').mkdir(exist_ok=True)
```

this should be no problem since the stdlib pathlib should be backwards compatible.

in order to make the change backwards compatible, you could make `setup.py` create both `pathlib.py` and a symlink named `pathlib2.py`

**Comment by mcmtroffaes** [comment]
Thanks for the suggestion, however pathlib and pathlib2 will diverge on any older Python platforms - so don't do that. Instead stick to pathlib2 on all your code if you need compatibility:

```python
from pathlib2 import ...
```

will suit all your needs. Once you no longer need the compatibility, you can then update your code by changing pathlib2 into pathlib.

**Comment by mcmtroffaes** [comment]
Also it's a bad idea to override stdlib packages (for lot's of reasons!!).

**Comment by flying-sheep** [comment]
override?

i thought the idea as to basically do:

1. use pathlib from the stdlib if available (don’t install pathlib or pathlib2 from pip)
2. use pathlib2 when on python ≤ 3.3

e.g. i have a project relying on pathlib, written under python 3.4 and 3.5.

it will handsomely run on python 3.3, if i install “pathlib2.py” as “pathlib.py”

**Comment by mcmtroffaes** [comment]
Well, that's a different suggestion. However that won't work either: someone might want to use pathlib2 on Python 3.4 to use features of pathlib that are only available on Python 3.5 or later.

It's ok for projects on themselves to rely on pathlib2 only on particular Python versions, however each project by itself should make this decision for itself, and depending on what is used from the pathlib API, that decision may vary across projects. The simplest approach however is simply to depend on pathlib2 for everything, for as long as you need, and only then switch to pathlib when you can drop the compatibility requirements (whenever that is).

Does this clarify?

**Comment by flying-sheep** [comment]
> someone might want to use pathlib2 on Python 3.4 to use features of pathlib that are only available on Python 3.5 or later.

ah, makes sense. then it really would shadow the builtin module.

> The simplest approach however is simply to depend on pathlib2 for everything, for as long as you need, and only then switch to pathlib when you can drop the compatibility requirements (whenever that is).

i.e. once you’re comfortable with requiring at least python 3.5, you can change pathlib2 → pathlib.

**Comment by mcmtroffaes** [comment]
Exactly - or more relaxedly, whenever your comfortable requiring at least the Python version whose pathlib API you need for your application (this could be just 3.4 if you don't use the latest fancy features).

**Comment by amcgregor** [comment]
Apologies for resurrecting an old thread, just wanted to make note of the ["correct" approach for declaring conditional Python version-specific dependencies](https://www.python.org/dev/peps/pep-0508/#environment-markers), which can be a touch difficult to find on the best of days.  In your `setup.py` under `install_requires` include the following:

```python
 ...
install_requires = ['pathlib2; python_version < "3.4"']
```

Replace `3.4` with `3.5` if you require the additional local path manipulation functions added in 3.5. I'm unhappy with the suggestion to install a package "for compatibility sake" even on versions where it's entirely unnecessary—we're not NPM, here, and the environment markers feature is quite handy.  ;P  (Here's hoping this doesn't accidentally re-open the ticket!)
