### ISSUE TITLE
compatibility issue in v2.3.7

### ISSUE THREAD

**Issue by IterableTrucks** [mcmtroffaes/pathlib2#80]
When installing new version of 2.3.7 on Python2.7, pip prompts error:
```
   from six.moves.collections_abc import Sequence

ImportError: No module named collections_abc
```

**Comment by mcmtroffaes** [comment]
Thanks for reporting. Which version of six are you using?

**Comment by IterableTrucks** [comment]
The version is 1.10.0. Fixed after upgrading six.

**Comment by mcmtroffaes** [comment]
I've done a quick post release, so pip should now automatically pick this up. Thanks again!
